"""
Modular AI provider system.
Switch providers via the AI_PROVIDER environment variable.
Supported: "mock" (default, no API key needed), "openai"
"""
from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any, Dict, List
import json
import re


class AIProvider(ABC):
    """Abstract base for all AI providers."""

    @abstractmethod
    async def extract_lab_results(self, text: str) -> Dict[str, Any]:
        """Extract structured lab results from report text."""

    @abstractmethod
    async def generate_summary(self, patient_info: Dict, results: List[Dict]) -> str:
        """Generate a patient-friendly summary (NOT diagnostic)."""


# ─── Mock Provider ────────────────────────────────────────────────────────────

class MockAIProvider(AIProvider):
    """Demo provider — works without any API key."""

    async def extract_lab_results(self, text: str) -> Dict[str, Any]:
        """
        Attempt simple regex-based extraction as a best-effort demo.
        Returns structured data in the same shape as a real LLM would.
        """
        results = []
        patterns = [
            # "Hemoglobin   13.5   g/dL   (12.0-17.5)"
            r"([A-Za-z][A-Za-z0-9 /\-]+?)\s{2,}([\d.]+)\s+([A-Za-z/%]+)\s+\(?([\d.]+-[\d.]+)\)?",
            # "Glucose: 95 mg/dL Ref: 70-100"
            r"([A-Za-z][A-Za-z0-9 /\-]+?):\s*([\d.]+)\s*([A-Za-z/%]+)[^\n]*(?:Ref|Reference|Range)[:\s]*([\d.]+-[\d.]+)",
        ]
        seen = set()
        for pattern in patterns:
            for m in re.finditer(pattern, text, re.IGNORECASE):
                name = m.group(1).strip()
                if name.lower() in seen:
                    continue
                seen.add(name.lower())
                results.append({
                    "test_name": name,
                    "value": m.group(2).strip(),
                    "unit": m.group(3).strip(),
                    "reference_range": m.group(4).strip(),
                    "observation": None,
                    "confidence": 0.70,
                })

        return {
            "report_date": None,
            "report_type": "Laboratory Report",
            "report_title": None,
            "lab_name": None,
            "doctor_name": None,
            "results": results,
            "provider": "mock",
        }

    async def generate_summary(self, patient_info: Dict, results: List[Dict]) -> str:
        name = patient_info.get("name", "the patient")
        total = len(results)
        abnormal = [r for r in results if r.get("status") in ("low", "high")]
        lines = [
            f"This report contains {total} laboratory result(s) for {name}.",
        ]
        if abnormal:
            names = ", ".join(r["test_name"] for r in abnormal[:5])
            lines.append(
                f"{len(abnormal)} result(s) fall outside the reference range provided "
                f"in the report ({names}). Please discuss these with your healthcare provider."
            )
        else:
            lines.append(
                "All extracted results appear to be within the reference ranges "
                "provided in the report."
            )
        lines.append(
            "\n⚠️ DISCLAIMER: This summary is for informational purposes only and has been "
            "automatically generated by MedLens. It is NOT a medical diagnosis, treatment "
            "recommendation, or professional medical advice. Always consult a qualified "
            "healthcare professional regarding your medical results."
        )
        return "\n\n".join(lines)


# ─── OpenAI-compatible Provider ──────────────────────────────────────────────

class OpenAIProvider(AIProvider):
    """Real LLM extraction via OpenAI (or any compatible endpoint)."""

    def __init__(self):
        from openai import AsyncOpenAI
        from app.config import settings
        self.client = AsyncOpenAI(
            api_key=settings.OPENAI_API_KEY,
            base_url=settings.OPENAI_BASE_URL,
        )
        from app.config import settings as s
        self.model = s.OPENAI_MODEL

    async def extract_lab_results(self, text: str) -> Dict[str, Any]:
        prompt = (
            "You are a medical document data extraction assistant. "
            "Extract all laboratory test results from the following medical report text. "
            "Return ONLY a valid JSON object with this exact schema:\n"
            "{\n"
            '  "report_date": "YYYY-MM-DD or null",\n'
            '  "report_type": "string or null",\n'
            '  "report_title": "string or null",\n'
            '  "lab_name": "string or null",\n'
            '  "doctor_name": "string or null",\n'
            '  "results": [\n'
            "    {\n"
            '      "test_name": "string",\n'
            '      "value": "string (exactly as written)",\n'
            '      "unit": "string or null",\n'
            '      "reference_range": "string exactly as written in report or null",\n'
            '      "observation": "any observation text exactly as written or null",\n'
            '      "confidence": 0.0-1.0\n'
            "    }\n"
            "  ]\n"
            "}\n\n"
            "IMPORTANT RULES:\n"
            "- Extract values EXACTLY as they appear. Do NOT interpret, diagnose, or classify.\n"
            "- Do NOT add LOW/NORMAL/HIGH labels. The application calculates that separately.\n"
            "- If a field is not found, use null.\n"
            "- Return only the JSON object, no markdown fences.\n\n"
            f"REPORT TEXT:\n{text[:8000]}"
        )

        response = await self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            response_format={"type": "json_object"},
        )
        raw = response.choices[0].message.content
        data = json.loads(raw)
        data["provider"] = "openai"
        return data

    async def generate_summary(self, patient_info: Dict, results: List[Dict]) -> str:
        name = patient_info.get("name", "the patient")
        results_text = "\n".join(
            f"- {r['test_name']}: {r['value_raw']} {r.get('unit','') or ''} "
            f"(ref: {r.get('ref_range_raw','N/A')}) — status: {r.get('status','unknown')}"
            for r in results
        )
        prompt = (
            f"Write a brief, plain-language summary for {name} about their laboratory results. "
            "Be factual and informational only. "
            "Do NOT provide any diagnosis, treatment recommendation, medication advice, "
            "or definitive medical conclusion. "
            "Explain what the results contain and note which values are outside the reference "
            "range provided in the report. "
            "End with a disclaimer that this is not medical advice.\n\n"
            f"Results:\n{results_text}"
        )
        response = await self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
        )
        return response.choices[0].message.content


# ─── Factory ─────────────────────────────────────────────────────────────────

def get_ai_provider() -> AIProvider:
    from app.config import settings
    provider = settings.AI_PROVIDER.lower()
    if provider == "mock":
        return MockAIProvider()
    elif provider in ("openai", "openai_compatible"):
        return OpenAIProvider()
    else:
        raise ValueError(f"Unknown AI_PROVIDER: {provider}")
